version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: tayyab
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: editProfile
    networks:
      - freecodecamp
networks: 
  freecodecamp: